server:
  port: 5000

localeTag: ru

logging:
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"
  level:
    org:
      springframework:
        web: info


telegram:
  org-bot: https://api.telegram.org/bot
  bot:
    botUserName: "@alekot_bot"
    botToken: 1370699371:AAFtToynML4gadnM7zfqjmn6DKQGOeSnaXc
    #ngrok
    webHookPath: https://3a5e60129a0e.ngrok.io
  channel:
    id: 1001300578419
#  Heroku
#  webHookPath: https://telegram-film-bot.herokuapp.com/

spring:
  data:
    mongodb:
      uri: mongodb+srv://songs_from_dumpster:songs_from_dumpster@aleksandrkotkovets.8mamm.mongodb.net/film_from_telegram_channel?retryWrites=true&w=majority

regex:
  message:
    get:
      genre: "Жанр:\\s*(.*?)\\nРейтинг:"
      rate: "Рейтинг:\\s*(\\d+)"
      year: "Год:\\s*(\\d+)\\nЖанр:"

keyboard:
  split-size: 3

film:
  top: 5

user:
  admin:
    id: 487721735

ping-task:
  url: https://www.google.com
  period: 1200000
