server:
  port: 5000

localeTag: ru

logging:
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"
  level:
    org:
      springframework:
        web: info

telegram-bot:
  botUserName: "@alekot_bot"
  botToken: 1370699371:AAFtToynML4gadnM7zfqjmn6DKQGOeSnaXc
#ngrok
  webHookPath: https://26695ec6feff.ngrok.io
#  Heroku
#  webHookPath: https://telegram-film-bot.herokuapp.com/

