server:
  port: 5000

localeTag: "ru-RU"

logging:
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"
  level:
    org:
      springframework:
        web: info

telegram-bot:
  botUserName: "@alekot_bot"
  botToken: 1370699371:AAFtToynML4gadnM7zfqjmn6DKQGOeSnaXc
  webHookPath: https://bb8a8d3cc261.ngrok.io
  proxyType: SOCKS5
  proxyHost: localhost
  proxyPort: 9150